### PR TITLE
update bootstrap and add dark mode

### PR DESCRIPTION
**Pull request by userlip**
I updated to the latest Bootstrap version and added the darkmode from the original repo.
Let me know if everything is alright, would do some more PRs soon then :)

### CODE REVIEW

**Review by zuramai — CHANGES_REQUESTED** [review]
Hi @userlip, thank you for your PR.

image

As you can see in image above, the sidebar does not change its color when switched to dark mode. 

I suppose you should also copy other `.scss` files (not only in the `themes/dark` folder) from the original mazer. There are many things that had changed to add the dark mode.

https://github.com/zuramai/laravel-mazer/blob/2d954855fe1878cdf2c4cec78039acd4acd5a232/resources/sass/components/_sidebar.scss#L22-L24

See the above code,  the `background-color` value is still `#fff` while in the original mazer is `$sidebar-bg`.

See the code below to how the original mazer's `sidebar.scss`
https://github.com/zuramai/mazer/blob/81af3c0440072702d48fe8c45ea4e0233c620e8e/src/assets/scss/components/_sidebar.scss#L22-L24

**Comment by userlip** [comment]
My bad. I am on it🤝

**Comment by userlip** [comment]
please check again @zuramai :)

**Review by zuramai — APPROVED** [review]
Looks nice!

**Pull request merged**
